function New-AdoMetricsReadme
{
    <#
.SYNOPSIS
Generates README markdown for Azure DevOps build metrics.

.DESCRIPTION
Creates a markdown report using canonical metric rows (as produced by ConvertTo-AdoMetricRow)
and the project/metrics profiles. This function performs no file I/O and returns a string.

.PARAMETER Rows
Canonical metric rows (typically from the cumulative JSONL store).

.PARAMETER ProjectProfile
Project profile object (Get-AdoProjectProfile).

.PARAMETER MetricsProfile
Metrics profile object (Get-AdoMetricsProfile). Reserved for future section layout control.

.OUTPUTS
System.String (markdown)

#>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][object[]]$Rows,
        [Parameter(Mandatory)][object]$ProjectProfile,
        [Parameter(Mandatory)][object]$MetricsProfile
    )

    $rows = @($Rows)

    # StrictMode-safe access for required-ish fields
    $org = if ($ProjectProfile.PSObject.Properties.Match('organization').Count -gt 0) { [string]$ProjectProfile.organization } else { "" }
    $proj = if ($ProjectProfile.PSObject.Properties.Match('project').Count -gt 0) { [string]$ProjectProfile.project }      else { "" }
    $defIds = if ($ProjectProfile.PSObject.Properties.Match('definitionIds').Count -gt 0 -and $null -ne $ProjectProfile.definitionIds)
    {
        @($ProjectProfile.definitionIds)
    }
    else
    {
        @()
    }

    $sb = New-Object System.Text.StringBuilder

    # Title resolution (supports both new and legacy shapes; StrictMode-safe)
    $title = "Azure DevOps Pipeline Metrics"

    # New shape: ProjectProfile.titles.readme
    if ($ProjectProfile.PSObject.Properties.Match('titles').Count -gt 0 -and
        $null -ne $ProjectProfile.titles -and
        $ProjectProfile.titles.PSObject.Properties.Match('readme').Count -gt 0 -and
        -not [string]::IsNullOrWhiteSpace([string]$ProjectProfile.titles.readme))
    {

        $title = [string]$ProjectProfile.titles.readme
    }
    # Legacy shape: ProjectProfile.readmeTitle
    elseif ($ProjectProfile.PSObject.Properties.Match('readmeTitle').Count -gt 0 -and
        -not [string]::IsNullOrWhiteSpace([string]$ProjectProfile.readmeTitle))
    {

        $title = [string]$ProjectProfile.readmeTitle
    }

    $null = $sb.AppendLine("# $title")
    if (-not [string]::IsNullOrWhiteSpace($org)) { $null = $sb.AppendLine("- Organization: $org") }
    if (-not [string]::IsNullOrWhiteSpace($proj)) { $null = $sb.AppendLine("- Project: $proj") }
    if ($defIds.Count -gt 0)
    {
        $null = $sb.AppendLine("- DefinitionIds: $($defIds -join ', ')")
    }
    $null = $sb.AppendLine()

    # Totals per pipeline
    $byPipe = @($rows | Group-Object pipeline | Sort-Object Name)
    $pipelineCount = $byPipe.Count

    $null = $sb.AppendLine("## Totals Per Pipeline (Pipelines: $pipelineCount)")
    $null = $sb.AppendLine()
    $null = $sb.AppendLine("| Pipeline | Runs | Completed | Succeeded | Failed | Canceled | Avg Duration (min) |")
    $null = $sb.AppendLine("|---|---:|---:|---:|---:|---:|---:|")

    foreach ($g in $byPipe)
    {
        $pipeRows = @($g.Group)
        $runs = $pipeRows.Count
        $completed = @($pipeRows | Where-Object { $_.status -eq "completed" }).Count
        $succeeded = @($pipeRows | Where-Object { $_.result -eq "succeeded" }).Count
        $failed = @($pipeRows | Where-Object { $_.result -eq "failed" }).Count
        $canceled = @($pipeRows | Where-Object { $_.result -eq "canceled" -or $_.result -eq "cancelling" }).Count

        $durSecs = @(
            foreach ($r in $pipeRows)
            {
                if ($null -ne $r.PSObject.Properties["durationSeconds"] -and $null -ne $r.durationSeconds)
                {
                    [double]$r.durationSeconds
                }
            }
        )

        $avgMin = ""
        if ($durSecs.Count -gt 0)
        {
            $avgSec = ($durSecs | Measure-Object -Average).Average
            $avgMin = Convert-ToRoundedMinutes -Seconds ([double]$avgSec)
        }

        $null = $sb.AppendLine("| $($g.Name) | $runs | $completed | $succeeded | $failed | $canceled | $avgMin |")
    }

    $null = $sb.AppendLine()

    # Weekly metrics index placeholder (consumer repo can extend)
    $null = $sb.AppendLine("## Weekly Metrics")
    $null = $sb.AppendLine()
    $null = $sb.AppendLine("> Weekly reports are generated by the consuming automation and indexed here.")
    $null = $sb.AppendLine()

    return $sb.ToString()
}
